### ISSUE TITLE
smallcases no longer use backtested data for statistics.

### ISSUE THREAD

**Issue by LonelyCpp** [indiainvestments/content#42]
the last two points in [the smallcase article](https://github.com/indiainvestments/content/blob/main/faqs/is-smallcase-a-good-investment-returns-look-good.md) need some changes at least. 

> **Smallcase loves selling "Backtested Models".**
>
> (...)
>
> It's possible for anyone who's basic interest in markets, to say what stocks would have done great for a decade, if purchased in 2010. A poorly executed "backtest" is a fancy version of looking back and picking winners.
> 
> **There are also some concerns around smallcase not being upfront with their numbers**
>
> They include backtested portfolio in computing returns of the smallcase, which is not at all how any asset management services report their returns. Start dates of the same portfolio also fluctuate, when checked at different dates.

The last point especially is no longer true. The platform only shows values (including CAGR) **since launch** of a smallcase. Backtested data is only shown in the "max" graph with makes the backtested data quite clear.

source - [smallcase blog](https://blog.smallcase.com/a-step-towards-making-smallcases-more-transparent/)

As to how these points need to be reworded, I cannot say since I work at smallcase and may be biased.

**Comment by crimelabs786** [comment]
Hey, thanks for bringing this to our notice. We'd update the entry in due time.

**Comment by crimelabs786** [comment]
[Have updated here, incorporating new information](https://indiainvestments.gitbook.io/content/faqs/stocks/is-smallcase-a-good-investment-returns-look-good).

Closing this issue for now. If you need to discuss this further, [please reach out to us on Discord](https://discord.gg/hqBNg4u)
